language: node_js
node_js:
  - "node"

before_script:
  - yarn flow-typed install
  - yarn flow

script:
  - yarn lint
  - yarn build

deploy:
  on:
    branch: master
  script:
  - now build --public --name=compass --token $NOW_TOKEN
  - now alias --token $NOW_TOKEN
